### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by michaeljota** [jprichardson/is-electron-renderer#2]
I'm trying to use this, but it trows this error in the browser. I'm wanna be able to switch code between browser and electron-renderer.

**Comment by jprichardson** [comment]
https://github.com/jprichardson/is-electron-renderer/blob/1506ae56d60100aea9842d46a8da7032b8fa7b5b/index.js#L3 should be changed to

``` js
if (typeof process === 'undefined') return true
```

PR accepted.

**Comment by michaeljota** [comment]
Does process is defined in browser?

**Comment by zeke** [comment]
☝️ no.

**Comment by michaeljota** [comment]
Thanks... 

I guess that this have to be used with `Webpack` or something like that. I guess I can set process accordly.
